"use client";

import { Area, AreaChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { EmployeeUsageRow, LeaveRequest } from "./leaveUsageTypes";
import { formatDays } from "./leaveUsageUtils";

const COLORS=["#6366f1","#06b6d4","#8b5cf6","#f59e0b","#ec4899","#10b981"];
const TOOLTIP_CONTENT_STYLE={backgroundColor:"#fff",border:"1px solid #e2e8f0",borderRadius:8,boxShadow:"0 4px 12px rgba(15,23,42,0.12)",fontSize:12,padding:"8px 12px"};
const TOOLTIP_ITEM_STYLE={color:"#0f172a"};
const TOOLTIP_LABEL_STYLE={color:"#475569",fontWeight:600,marginBottom:4};
function barColor(rate:number){return rate>=90?"bg-rose-500":rate>=70?"bg-indigo-500":rate>=50?"bg-cyan-500":"bg-emerald-500";}
export function DepartmentUsage({rows}:{rows:EmployeeUsageRow[]}){const groups=new Map<string,{used:number;total:number}>();rows.forEach(row=>{const name=row.departmentName||"미지정";const group=groups.get(name)??{used:0,total:0};group.used+=row.usedDays;group.total+=row.totalDays;groups.set(name,group);});const data=[...groups].map(([name,value])=>({name,rate:value.total?Number((value.used/value.total*100).toFixed(1)):0})).sort((a,b)=>b.rate-a.rate);return <section className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm"><h2 className="mb-5 text-lg font-bold text-gray-900">부서별 연차 사용률</h2><div className="max-h-64 space-y-4 overflow-auto">{data.length?data.map(item=><div key={item.name}><div className="mb-1.5 flex justify-between text-sm"><span className="font-medium text-gray-700">{item.name}</span><strong>{item.rate}%</strong></div><div className="h-2 rounded-full bg-gray-100"><div className={`h-full rounded-full ${barColor(item.rate)}`} style={{width:`${item.rate}%`}} role="progressbar" aria-valuenow={item.rate} aria-valuemin={0} aria-valuemax={100}/></div></div>):<p className="py-16 text-center text-sm text-gray-500">집계 가능한 부서 데이터가 없습니다.</p>}</div></section>;}
export function MonthlyUsageTrend({requests}:{requests:LeaveRequest[]}){const data=Array.from({length:12},(_,index)=>({month:`${index+1}월`,usedDays:0}));requests.filter(r=>r.status==="APPROVED"&&r.startDate.slice(0,7)===r.endDate.slice(0,7)).forEach(r=>{data[Number(r.startDate.slice(5,7))-1].usedDays+=Number(r.leaveDays);});return <section className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-bold text-gray-900">월별 연차 사용 추이</h2><p className="mt-1 text-xs text-gray-400">한 달 안에서 종료된 승인 휴가 기준</p><div className="mt-4 h-60"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{left:-18,right:8}}><CartesianGrid stroke="#eef2f7" vertical={false}/><XAxis dataKey="month" tick={{fontSize:11,fill:"#94a3b8"}} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:11,fill:"#94a3b8"}} axisLine={false} tickLine={false}/><Tooltip formatter={(value)=>[`${formatDays(Number(value))}일`,"사용 연차"]} contentStyle={TOOLTIP_CONTENT_STYLE} itemStyle={TOOLTIP_ITEM_STYLE} labelStyle={TOOLTIP_LABEL_STYLE}/><Area type="monotone" dataKey="usedDays" stroke="#6366f1" fill="#eef2ff" strokeWidth={2} animationDuration={300}/></AreaChart></ResponsiveContainer></div></section>;}
export function LeaveTypeDistribution({requests}:{requests:LeaveRequest[]}){const groups=new Map<string,number>();requests.filter(r=>r.status==="APPROVED").forEach(r=>groups.set(r.leaveTypeName,(groups.get(r.leaveTypeName)??0)+Number(r.leaveDays)));const items=[...groups].map(([name,value])=>({name,value}));const total=items.reduce((sum,item)=>sum+item.value,0);const chart=total?items:[{name:"데이터 없음",value:1}];return <section className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-bold text-gray-900">휴가 유형별 사용 비율</h2><div className="relative mx-auto h-44"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={chart} dataKey="value" innerRadius={46} outerRadius={66} stroke="none" isAnimationActive={false}>{chart.map((_,index)=><Cell key={index} fill={total?COLORS[index%COLORS.length]:"#e5e7eb"}/>)}</Pie></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 flex flex-col items-center justify-center"><strong className="text-xl">{formatDays(total)}일</strong><span className="text-xs text-gray-500">총 사용 일수</span></div></div><div className="space-y-2">{items.map((item,index)=><div key={item.name} className="flex justify-between text-sm"><span className="flex items-center gap-2 text-gray-600"><i className="h-2.5 w-2.5 rounded-full" style={{background:COLORS[index%COLORS.length]}}/>{item.name}</span><strong>{total?(item.value/total*100).toFixed(1):0}% ({formatDays(item.value)}일)</strong></div>)}{!items.length&&<p className="text-center text-sm text-gray-500">승인된 휴가 사용 내역이 없습니다.</p>}</div></section>;}
