"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { DepartmentUsage, LeaveTypeDistribution, MonthlyUsageTrend } from "./LeaveUsageCharts";
import { EmployeeUsageModal, EmployeeUsageTable } from "./EmployeeLeaveUsage";
import LeaveUsageStats from "./LeaveUsageStats";
import type { Department, EmployeePage, EmployeeUsageRow, LeaveBalance, LeaveRequest, Position, SortKey, UsageFilters } from "./leaveUsageTypes";
import { makeRows, summarize, yearRange } from "./leaveUsageUtils";

const API_BASE_URL=process.env.NEXT_PUBLIC_API_BASE_URL??"http://localhost:8081/api";
function authHeaders():HeadersInit{const token=localStorage.getItem("accessToken")??sessionStorage.getItem("accessToken");return token?{Authorization:`Bearer ${token}`}:{}}function initial():UsageFilters{return{...yearRange(),keyword:"",departmentId:"",positionId:""};}function csv(value:string|number){return `"${String(value).replaceAll('"','""')}"`;}
export default function LeaveUsageDashboard(){const [allRows,setAllRows]=useState<EmployeeUsageRow[]>([]);const [requests,setRequests]=useState<LeaveRequest[]>([]);const [departments,setDepartments]=useState<Department[]>([]);const [positions,setPositions]=useState<Position[]>([]);const [draft,setDraft]=useState<UsageFilters>(initial);const [filters,setFilters]=useState<UsageFilters>(initial);const [page,setPage]=useState(0);const [pageSize,setPageSize]=useState(10);const [selected,setSelected]=useState<number[]>([]);const [sortKey,setSortKey]=useState<SortKey>("usageRate");const [direction,setDirection]=useState<"asc"|"desc">("desc");const [detail,setDetail]=useState<EmployeeUsageRow|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const [retry,setRetry]=useState(0);const [balanceWarning,setBalanceWarning]=useState(false);
useEffect(()=>{let cancelled=false;async function load(){setLoading(true);setError(null);try{const [employeesRes,leaveRes,deptRes,posRes]=await Promise.all([fetch(`${API_BASE_URL}/employees?page=0&size=1000`),fetch(`${API_BASE_URL}/leave-requests`,{headers:authHeaders()}),fetch(`${API_BASE_URL}/departments`),fetch(`${API_BASE_URL}/positions`)]);if(!employeesRes.ok||!leaveRes.ok||!deptRes.ok||!posRes.ok)throw new Error();const [employeePage,leaves,depts,pos]=await Promise.all([employeesRes.json() as Promise<EmployeePage>,leaveRes.json() as Promise<LeaveRequest[]>,deptRes.json() as Promise<Department[]>,posRes.json() as Promise<Position[]>]);const active=(employeePage.content??[]).filter(e=>e.employeeStatusCode==="ACTIVE");const balanceResults=await Promise.allSettled(active.map(async employee=>{const response=await fetch(`${API_BASE_URL}/leave-balances?employeeId=${employee.employeeId}`,{headers:authHeaders()});if(!response.ok)throw new Error();return [employee.employeeId,await response.json() as LeaveBalance[]] as const;}));const balanceMap=new Map<number,LeaveBalance[]>();balanceResults.forEach(result=>{if(result.status==="fulfilled")balanceMap.set(result.value[0],result.value[1]);});if(!cancelled){setAllRows(makeRows(active,balanceMap,Array.isArray(leaves)?leaves:[]));setRequests(Array.isArray(leaves)?leaves:[]);setDepartments(depts);setPositions(pos);setBalanceWarning(balanceResults.some(r=>r.status==="rejected"));setSelected([]);}}catch{if(!cancelled)setError("휴가 사용 현황을 불러오지 못했습니다.");}finally{if(!cancelled)setLoading(false);}}load();return()=>{cancelled=true;};},[retry]);
const departmentName=departments.find(d=>String(d.departmentId)===filters.departmentId)?.departmentName;const positionName=positions.find(p=>String(p.positionId)===filters.positionId)?.positionName;const filtered=useMemo(()=>allRows.filter(row=>{const key=filters.keyword.trim().toLocaleLowerCase();return(!key||row.name.toLocaleLowerCase().includes(key)||(row.departmentName??"").toLocaleLowerCase().includes(key)||row.employeeNo.toLocaleLowerCase().includes(key))&&(!departmentName||row.departmentName===departmentName)&&(!positionName||row.positionName===positionName);}).sort((a,b)=>(a[sortKey]-b[sortKey])*(direction==="asc"?1:-1)),[allRows,departmentName,direction,filters.keyword,positionName,sortKey]);const periodRequests=useMemo(()=>requests.filter(r=>r.startDate>=filters.startDate&&r.endDate<=filters.endDate),[filters.endDate,filters.startDate,requests]);const summary=summarize(filtered);const pageRows=filtered.slice(page*pageSize,(page+1)*pageSize);
const download=useCallback(()=>{const target=selected.length?filtered.filter(row=>selected.includes(row.employeeId)):filtered;const headers=["사번","이름","부서","직급","연차 지급 일수","연차 사용 일수","연차 잔여 일수","연차 사용률"];const lines=target.map(row=>[row.employeeNo,row.name,row.departmentName||"-",row.positionName||"-",row.totalDays,row.usedDays,row.remainDays,`${row.usageRate}%`]);const url=URL.createObjectURL(new Blob([`\uFEFF${[headers,...lines].map(line=>line.map(csv).join(",")).join("\r\n")}`],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=`leave-usage-${new Date().toISOString().slice(0,10)}.csv`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);},[filtered,selected]);useEffect(()=>{const report=()=>window.print();window.addEventListener("leave:usage-report",report);return()=>window.removeEventListener("leave:usage-report",report);},[]);
return <div className="leave-usage-print mx-auto max-w-[1600px] space-y-5 pb-8"><div className="hidden print:block"><h1 className="text-2xl font-bold">휴가 사용 현황 리포트</h1><p className="text-sm">조회 기간: {filters.startDate} ~ {filters.endDate} · 출력일: {new Date().toLocaleDateString("ko-KR")}</p></div>{error&&<div className="leave-usage-no-print flex justify-between rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700"><span>{error}</span><button type="button" onClick={()=>setRetry(k=>k+1)}>재시도</button></div>}{balanceWarning&&<p className="leave-usage-no-print rounded-lg bg-amber-50 p-3 text-sm text-amber-700">일부 직원의 연차 잔액을 불러오지 못했습니다.</p>}<LeaveUsageStats summary={summary} loading={loading}/><div className="grid grid-cols-1 gap-4 xl:grid-cols-[1fr_1.35fr_0.85fr]"><DepartmentUsage rows={filtered}/><MonthlyUsageTrend requests={periodRequests}/><LeaveTypeDistribution requests={periodRequests}/></div><EmployeeUsageTable draft={draft} departments={departments} positions={positions} rows={pageRows} total={filtered.length} page={page} pageSize={pageSize} selected={selected} sortKey={sortKey} sortDirection={direction} loading={loading} onDraft={next=>setDraft(current=>({...current,...next}))} onApply={()=>{if(draft.startDate.slice(0,4)!==draft.endDate.slice(0,4)){alert("현재 API는 한 연도 범위 조회만 지원합니다.");return;}setFilters(draft);setPage(0);setSelected([]);}} onDownload={download} onPage={next=>{setPage(next);setSelected([]);}} onPageSize={size=>{setPageSize(size);setPage(0);setSelected([]);}} onToggle={id=>setSelected(ids=>ids.includes(id)?ids.filter(x=>x!==id):[...ids,id])} onToggleAll={()=>{const ids=pageRows.map(r=>r.employeeId);setSelected(ids.every(id=>selected.includes(id))?selected.filter(id=>!ids.includes(id)):[...new Set([...selected,...ids])]);}} onSort={key=>{if(sortKey===key)setDirection(value=>value==="asc"?"desc":"asc");else{setSortKey(key);setDirection("desc");}setPage(0);setSelected([]);}} onDetail={setDetail}/>{detail&&<EmployeeUsageModal row={detail} onClose={()=>setDetail(null)}/>}</div>;}
