"use client";

import { CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { DailyTrendPoint, MonthlyViewData } from "./monthlyAttendanceTypes";

const COLORS = ["#16a34a", "#d97706", "#e11d48", "#0891b2"];
const TOOLTIP_CONTENT_STYLE = { backgroundColor: "#fff", border: "1px solid #e2e8f0", borderRadius: 8, boxShadow: "0 4px 12px rgba(15,23,42,0.12)", fontSize: 12, padding: "8px 12px" };
const TOOLTIP_ITEM_STYLE = { color: "#0f172a" };
const TOOLTIP_LABEL_STYLE = { color: "#475569", fontWeight: 600, marginBottom: 4 };

export function DailyAttendanceTrend({ month, data, loading }: { month: string; data: DailyTrendPoint[]; loading: boolean }) {
  const today = new Date();
  const todayMonth = `${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, "0")}`;
  return <section className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-3"><h2 className="text-lg font-bold text-gray-900">일별 출근율 추이</h2><span className="rounded-full bg-indigo-50 px-2.5 py-1 text-xs font-semibold text-indigo-600">{Number(month.slice(0, 4))}년 {Number(month.slice(5))}월</span></div>{loading ? <div className="flex h-[240px] items-center justify-center text-sm text-gray-500">로딩 중...</div> : data.length === 0 ? <div className="flex h-[240px] items-center justify-center text-sm text-gray-500">선택한 월의 근태 데이터가 없습니다.</div> : <div className="h-[240px] w-full"><ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{ top: 12, right: 12, left: -16, bottom: 0 }}><CartesianGrid stroke="#eef2f7" vertical={false} /><XAxis dataKey="day" tick={{ fill: "#94a3b8", fontSize: 11 }} axisLine={false} tickLine={false} /><YAxis domain={[0, 100]} tickFormatter={(value) => `${value}%`} tick={{ fill: "#94a3b8", fontSize: 11 }} axisLine={false} tickLine={false} /><Tooltip labelFormatter={(day) => `${Number(month.slice(5))}월 ${day}일`} formatter={(value) => `${Number(value).toFixed(1)}%`} contentStyle={TOOLTIP_CONTENT_STYLE} itemStyle={TOOLTIP_ITEM_STYLE} labelStyle={TOOLTIP_LABEL_STYLE} /><Legend iconType="circle" iconSize={8} /><Line name="출근율" type="monotone" dataKey="attendanceRate" stroke="#6366f1" strokeWidth={2} dot={{ r: 2 }} connectNulls={false} animationDuration={300} /><Line name="지각률" type="monotone" dataKey="lateRate" stroke="#d97706" strokeWidth={1.5} dot={false} connectNulls={false} animationDuration={300} /><Line name="결근율" type="monotone" dataKey="absentRate" stroke="#e11d48" strokeWidth={1.5} dot={false} connectNulls={false} animationDuration={300} />{month === todayMonth && <ReferenceLine x={today.getDate()} stroke="#818cf8" strokeDasharray="4 4" label={{ value: "오늘", fill: "#6366f1", fontSize: 11 }} />}</LineChart></ResponsiveContainer></div>}</section>;
}

export function MonthlyAttendanceDonut({ data, loading }: { data: MonthlyViewData | null; loading: boolean }) {
  const items = [{ name: "정상출근", value: data?.normalCount ?? 0 }, { name: "지각", value: data?.lateCount ?? 0 }, { name: "결근", value: data?.absentCount ?? 0 }, { name: "휴가", value: data?.leaveCount ?? 0 }];
  const total = items.reduce((sum, item) => sum + item.value, 0);
  const chartData = total ? items : [{ name: "데이터 없음", value: 1 }];
  return <section className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-bold text-gray-900">월간 출결 현황</h2>{loading ? <div className="flex h-44 items-center justify-center text-sm text-gray-500">로딩 중...</div> : <><div className="relative mx-auto h-44 w-full"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={chartData} dataKey="value" nameKey="name" innerRadius={48} outerRadius={68} paddingAngle={total ? 2 : 0} stroke="none" isAnimationActive={false}>{chartData.map((_, index) => <Cell key={index} fill={total ? COLORS[index] : "#e5e7eb"} />)}</Pie></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 flex flex-col items-center justify-center"><strong className="text-xl text-gray-900">{data?.attendanceRate ?? 0}%</strong><span className="text-xs text-gray-500">출근율</span></div></div><div className="space-y-2">{items.map((item, index) => <div key={item.name} className="flex items-center justify-between text-sm"><span className="flex items-center gap-2 text-gray-600"><span className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: COLORS[index] }} />{item.name}</span><span className="font-semibold text-gray-900">{item.value}건 <span className="ml-1 text-xs font-normal text-gray-400">{total ? ((item.value / total) * 100).toFixed(1) : "0.0"}%</span></span></div>)}</div></>}</section>;
}
